import React from "react";
import Head from "next/head";
import IconButton from "@mui/material/IconButton";
import { Box } from "@mui/system";
import MenuIcon from "@mui/icons-material/Menu";
import SideBarMenu from "../components/SideBarMenu";
import { Typography } from "@mui/material";

export default function Home() {
  const [hideMenu, setHideMenu] = React.useState(true);

  function handleMenuClick() {
    hideMenu ? setHideMenu(false) : setHideMenu(true);
  }
  return (
    <Box>
      <Head>
        <title>TommyJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        style={{
          display: "flex",
        }}
      >
        <Box
          style={{
            position: "fixed",
          }}
        >
          <IconButton onClick={handleMenuClick}>
            <MenuIcon
              style={{
                color: "#e5e5e5",
              }}
            />
          </IconButton>
          {hideMenu ? null : <SideBarMenu />}
        </Box>
        <Box
          style={{
            // backgroundImage: `url(/blog-const.webp)`,
            // backgroundSize: "100% 100%",
            // backgroundRepeat: "no-repeat",
            alignItems: "center",
            display: "flex",
            flexDirection: "column",
            width: "100%",
            minHeight: "100vh",
          }}
        >
          <Typography
            variant="h4"
            style={{
              color: "#e5e5e5",
              marginTop: "3%",
            }}
          >
            React Javascript CSS
          </Typography>
          <Typography
            variant="h6"
            style={{
              color: "#e5e5e5",
              marginTop: "2%",
            }}
          >
            This site is under construction!
          </Typography>
        </Box>
      </Box>
    </Box>
  );
}
